

language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed johananoa/udagram-api-feed:v1
  - docker tag udagram-api-user johananoa/udagram-api-feed:v1
  - docker tag udagram-frontend johananoa/udagram-api-feed:v1
  - docker tag udagram-api-feed johananoa/reverseproxy:v1
  
 

after_success:
  - echo "$DOCKER_PASSWORD" |docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push johananoa/udagram-frontend:v1
  - docker push johananoa/udagram-api-feed:v1
  - docker push johananoa/udagram-api-user:v1
  - docker push johananoa/reverseproxy:v1
